version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile  
    volumes:
      - ./src:/var/www/html  
    ports:
      - "80:80" 
    networks:
      - my_network

  mysql:
    image: mysql:latest  
    volumes:
      - ./mysql-data:/var/lib/mysql  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beacon_bpl
      MYSQL_USER: abir
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"  
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1  
    ports:
      - "8090:80"  
    networks:
      - my_network
    depends_on:
      - mysql  

networks:
  my_network:
volumes:
  mysql-data:

